### ISSUE TITLE
is not valid or is empty after intersection with the surrounding geometry `geom`

### ISSUE THREAD

**Issue by flashpixx** [WZBSocialScienceCenter/geovoronoi#10]
Hello,

I would like to use the voronoi tesselation to aggregate points. I have got a data set with routing points of the baltic and north sea, so i'm using a shape file for the bounding box and read the points which are stored in a CSV file as WGS84 points. After that I try to generate the voronoi tesselation but it breaks with the error: `generated polygon is not valid or is empty after intersection with the surrounding geometry 'geom'`. How can I debug this error or fix it?
This is the code:

```python
import pandas as pd
import geopandas as gp
import geovoronoi as gv
import geovoronoi.plotting as gvp

boundary = gp.read_file("northbalticsea.shx").geometry[0]
df = pd.read_csv('data.csv.gz', parse_dates=[0, ])

df = gp.GeoDataFrame(df, crs="EPSG:4326", geometry=gp.points_from_xy(df.LONGITUDE, df.LATITUDE))
region_polys, region_pts = gv.voronoi_regions_from_coords(df["geometry"], boundary)

fig, ax = gvp.subplot_for_map()
gvp.plot_voronoi_polys_with_points_in_area(ax, boundary, region_polys, df["geometry"], region_pts)
plt.show()
```

In my case my `data.csv.gz` contains routes in the sea, so it could be possible, that some regions contains no data points

**Comment by flashpixx** [comment]
I think I need to clearify it a litte bit. I would like to create clusters for the ocean and I can guarantee, that all my points within the shape boundaries (in my use-case I have as boundary north and baltic sea and some sampled shipping routes in baltic and north sea). But in this case there can be clusters which are complete empty, and I think this is the problem. See the screenshot, the read solid lines are the boundaries of the shape and also the landside is the boundary. The black dashed lines are my sampled points.
<img width="1469" alt="example" src="https://user-images.githubusercontent.com/1868222/111278981-7db26300-863a-11eb-9e84-e9ca872ad514.png">

**Comment by internaut** [comment]
I think I understand, but I can't tell you what the problem is without the data. I'm also not sure if Voronoi regions are really appropriate for your use-case. They don't cluster points. In fact it's quite the opposite, as there will be a hull generated around *each single point*. Your points may be very near to each other, possibly causing numerical issues during computation which in turn cause the error that you described initially.

**Comment by flashpixx** [comment]
Yes I'm assuming this as well, but in this case a better error message could be helpful. Thanks for this nice discussion
