### ISSUE TITLE
RuntimeError: ridge line must intersect with surrounding geometry from `geom`

### ISSUE THREAD

**Issue by Irene-GM** [WZBSocialScienceCenter/geovoronoi#12]
Hi,

I have a set of points over the Netherlands and also the polygon of the country, both in `.shp` format. Originally, both the points and the polygon were encoded in `EPSG:4326` (WGS84), but they were also reprojected to `EPSG:3395` (Web Mercator). For the record, the polygon is actually a `MultiPolygon` type. 

So I ran the following code:

```python
from shapely.ops import cascaded_union
from geovoronoi.plotting import subplot_for_map, plot_voronoi_polys_with_points_in_area
from geovoronoi import voronoi_regions_from_coords, points_to_coords

# Read shapefile 
gdf = gpd.read_file(path_loc) 
print(gdf.head())
print("Dataframe CRS:", gdf.crs)

boundary = gpd.read_file(path_nl)
gdf_proj = gdf.to_crs(boundary.crs)
print("Boundary CRS: ", boundary.crs)

boundary_shape = cascaded_union(boundary.geometry)
coords = points_to_coords(gdf_proj.geometry)

# Calculate Voronoi Regions
poly_shapes, pts, poly_to_pt_assignments = voronoi_regions_from_coords(coords, boundary_shape)
```

But unfortunately the program ends with the following error:

```python

  station_id  longitude  ...        Y_webm                        geometry
0        279   6.572446  ...  6.902455e+06  POINT (731641.307 6902454.683)
1        225   4.554683  ...  6.850046e+06  POINT (507024.938 6850045.637)
2        235   4.780770  ...  6.935182e+06  POINT (532192.902 6935182.126)
3        240   4.789374  ...  6.823666e+06  POINT (533150.640 6823666.308)
4        242   4.920471  ...  6.993052e+06  POINT (547744.338 6993052.456)

[5 rows x 9 columns]

Dataframe CRS: {'init': 'epsg:3395'}
Boundary CRS:  {'init': 'epsg:3395'}

Traceback (most recent call last):
  File "[MYPATH]/eda/00_make_voronoi_diagram.py", line 41, in <module>
    poly_shapes, pts, poly_to_pt_assignments = voronoi_regions_from_coords(coords, boundary_shape)
  File "[MYPATH]/miniconda3/envs/defpy37/lib/python3.7/site-packages/geovoronoi/_voronoi.py", line 202, in voronoi_regions_from_coords
    geom_polys, geom_pts = region_polygons_from_voronoi(vor, geom, return_point_assignments=True, **kwargs)
  File "[MYPATH]/miniconda3/envs/defpy37/lib/python3.7/site-packages/geovoronoi/_voronoi.py", line 364, in region_polygons_from_voronoi
    raise RuntimeError('ridge line must intersect with surrounding geometry from `geom`')
RuntimeError: ridge line must intersect with surrounding geometry from `geom`
```
I also tried the same procedure, but using WGS84 first, then EPSG:28992 (official CRS of the Netherlands) for both datasets, but getting the same error. Since I am not sure of the source of the problem, I thought I could open this issue to see if I can get some more info on the error and perhaps some hints to fix this problem. 

Thanks a lot for your help!  :-)

**Comment by internaut** [comment]
It's hard to know what the problem is without having the data or at least a plot of the points and the surrounding shape.

Are you sure that all points lie within the surrounding shape? Do you have points that lie extremely close together or does the surrounding shape have some sort of tiny holes (the latter can happen with `cascaded_union`)? All this can lead to problems during the tessellation process.

**Comment by Irene-GM** [comment]
Hi again,

Thanks for your response; I am now attaching an image with the polygon and the points:

![image](https://user-images.githubusercontent.com/8654047/119997420-03a24100-bfd0-11eb-928f-89eefc1be0a6.png)

Now that you made a couple of mentions about the topology of the points being important, could it be that there are a few points laying outside the land borders of the country?

**Comment by internaut** [comment]
Yes that looks like some points are outside the shape, you should try filtering them out.

**Comment by Irene-GM** [comment]
I filtered the points out, but unfortunately the error was still showing. Since my intention was to make a quick visualization, in the end I just used `scipy.spatial.Voronoi` for that purpose. Not very pretty, but for my current purpose its just ok. Perhaps in the future I have more time to dig into this problem if it appears again. Thanks for reading, though! :-)
