### ISSUE TITLE
cascaded_union deprecation warning

### ISSUE THREAD

**Issue by trimble** [WZBSocialScienceCenter/geovoronoi#16]
I receive the following warning often when using `geovoronoi.voronoi_regions_from_coords()`:

"The 'cascaded_union()' function is deprecated. Use 'unary_union()' instead."

Looks like there might be just one place in the actual code that uses `cascaded_union()`: https://github.com/WZBSocialScienceCenter/geovoronoi/blob/a997fd56a27ea7566f7dad38ea102c382383773a/geovoronoi/_voronoi.py#L443

...and a couple of places in examples and tests...

I'll see about submitting a PR to update.

**Comment by internaut** [comment]
Thanks, this was fixed with the latest release.
