### ISSUE TITLE
Voronoi tool doesn't voronoi properly

### ISSUE THREAD

**Issue by openSourcerer9000** [WZBSocialScienceCenter/geovoronoi#19]
I thought I'd finally found the holy grail - a voronoi tool in python. Unfortunately, the results come out all janky. Below is the data and code to recreate this unlovable monster. You can compare it against the QGIS voronoi tool.
![image](https://user-images.githubusercontent.com/61931826/209880433-977030d0-6565-4b14-9d6b-769dea5d1a43.png)

[points.zip](https://github.com/WZBSocialScienceCenter/geovoronoi/files/10316710/points.zip)

```
import geovoronoi as gv
from shapely.geometry import box
from pathlib import Path
import pandas as pd, numpy as np
import geopandas as gpd,
g = 'geometry'

pts = gpd.read_file('points.gpkg')
ptz = pts[g].to_list()
crds = gv.points_to_coords(ptz)

bbox = coordz.dissolve().bounds
bbox = box(*bbox.iloc[0].to_list())
bbox
polys,_ = gv.voronoi_regions_from_coords(crds,bbox,per_geom=False)
vor = gpd.GeoSeries(polys,crs=pts.crs)
vor
gdf= gpd.GeoDataFrame(geometry=vor,crs=vor.crs)
gdf
gdf.to_file('uglyVoronoi.gpkg')
```

**Comment by internaut** [comment]
Sorry, but after changing employers I can't actively maintain this project any more (I will put a notice in the README).

Have you checked out [shapely's `voronoi_polygons`](https://shapely.readthedocs.io/en/stable/reference/shapely.voronoi_polygons.html#shapely.voronoi_polygons) function? It didn't exist when I wrote the geovoronoi package, but I think it provides basically the same functionality now and uses the GEOS C++ library in the background, which should also be faster and I *think* it's the same that QGIS uses (didn't check it).
