### ISSUE TITLE
Unable to plot Voronoi plot

### ISSUE THREAD

**Issue by RefenRefen** [WZBSocialScienceCenter/geovoronoi#20]
Hi!
I am trying to run the example that you placed on the first page. But a got an error that is the same for other examples that I have found all over the internet. It will happen when I call `plot_voronoi_polys_with_points_in_area(ax, area_shape, region_polys, coords, region_pts)`  The error is as follows: 

` {
	"name": "IndexError",
	"message": "too many indices for array: array is 0-dimensional, but 2 were indexed",
}`
For reproducing this error you should just run your example.

**Comment by internaut** [comment]
The error happens in the package *descartes*, not geovoronoi. It's probably a dependency problem: some newer version of descartes expects the data in a different format etc. I don't maintain the package any more so I won't be able to fix that. Please also note the disclaimer in the README:

> This package is currently not maintained. You may prefer to use the [voronoi_polygons function from the shapely package](https://shapely.readthedocs.io/en/stable/reference/shapely.voronoi_polygons.html#shapely.voronoi_polygons) instead, which didn't exist when I created the geovoronoi package, but is now considered to be a faster and more reliable option for generating Voronoi regions.

**Comment by RefenRefen** [comment]
Thank you for your answer. I suppose I've found another way to do that.
