### ISSUE TITLE
Example in transitioning to Shapely's functions

### ISSUE THREAD

**Issue by jacksongoode** [WZBSocialScienceCenter/geovoronoi#21]
Hi,

We've been trying to switch to Shapely's implementation as per your suggestion but are having trouble. Our previous example looked something like this:

```py
# Old approach
# Now get coords in the correct format
coords = points_to_coords(s_gpd.geometry)
region_polys, region_pts = voronoi_regions_from_coords(coords, bounding_shape)

# Reconstruct a dataframe with points and polys
s_gpd["site_voronoi"] = pd.Series()

# Loop through the region polys and assign them to the correct index of points
for key in region_polys:
    idx = region_pts[key][0]
    s_gpd.loc[s_gpd.index[idx], "site_voronoi"] = region_polys[key]
```

and we think the new approach would just be:
```py
# New approach with Shapely
s_gpd["new_site_voronoi"] = voronoi_polygons(s_gpd.geometry, extend_to=bounding_shape)
```

But this seems to give a series of multipoint geometry with the bounding shape completely filled. Do you have any suggestions as to why that might be?

**Comment by internaut** [comment]
Sorry, but I neither maintain Shapely nor do I maintain or provide support for this repository anymore since I switched jobs. I simply don't have the time for this in my spare time. I suggest you head over to the Shapely documentation / GitHub issues for that question.

**Comment by jacksongoode** [comment]
Okay thank you!
