### ISSUE TITLE
Shapes need rewinding when converted to geojson?

### ISSUE THREAD

**Issue by psychemedia** [WZBSocialScienceCenter/geovoronoi#3]
Hi 

I'm a naive geo user rather than a geo-expert and whilst trying to use outputs from the (really useful - thanks:-) `geovoronoi` package to plot choropleth maps using the `folium` package, I found the geo-json created from a geopandas representation of the data was invalid.

```
from geovoronoi import voronoi_regions_from_coords, points_to_coords

# convert the pandas Series of Point objects to NumPy array of coordinates
coords = points_to_coords(gdf.Coordinates)

# Calculate the Voronoi regions for the identifed points and then 
# clip within the geographic area shape
poly_shapes, pts, poly_to_pt_assignments = voronoi_regions_from_coords(coords, boundary_shape)

gdf['voronoi_boundary'] = poly_shapes
gdf = gdf.set_geometry('voronoi_boundary')
```

However, I could fix it with the following:

```python
import json
from geojson_rewind import rewind

gdf = gdf.set_geometry('voronoi_boundary')
rewoundGeoJSON = rewind( json.dumps(gdf['voronoi_boundary'].__geo_interface__) )
```

The `rewoundGeoJSON` was then well formed and I could use it as the boundaryfile to generate a `folium.Choropleth()` map.

In the workflow, I'm not sure where the co-ordinate winding is most appropriately handled, or what the side effects of various windings are?

**Comment by internaut** [comment]
Sorry, can't help with this. Maybe you can try it out with the new version 0.3.0, which implements a new algorithm for generating the Voronoi region polygons.
