### ISSUE TITLE
O(N^2) assignment of points to cells

### ISSUE THREAD

**Issue by meitiv** [WZBSocialScienceCenter/geovoronoi#6]
I noticed that part after computing the polygons the code assigns all points to these polygons.  This results in an O(N^2) implementation which is untenable (memory and speed) when there are a lot of points (I have 200000).  Assigning most points to cells by computing the matrix of distances is unnecessary.  Most points (90-95%) are unambiguously assigned by Voronoi from scipy.spatial.  It would be fantastic if the library (which is definitely filling a much needed niche) could be sped up by using these unambiguous assignments to cells that don't have edges that extend to infinity.

Thanks!

**Comment by internaut** [comment]
Good point. Haven't looked into the code for a while, but I think your strategy should work. Currently I don't have the time to implement it, but I have it on my list. However, please feel free to suggest an update via PR, this would be much appreciated!

**Comment by internaut** [comment]
Had the time to actually work on this and I got a version that is much faster and memory efficient on branch `issue_6`. Will have to do some more testing but I think a new version of geovoronoi with this update can be expected in the next few weeks.

**Comment by internaut** [comment]
A new, faster algorithm was implemented in version 0.3.0, which is now available on PyPI.
