### ISSUE TITLE
areas (km² or m²) does not seem to work

### ISSUE THREAD

**Issue by nico-bock** [WZBSocialScienceCenter/geovoronoi#9]
I liked to calculate the areas of the voronoi regions,
but in my example they was much smaller than they should be (0.11715301m² for whole of Berlin). 

When I tried do fix the bug, I took a look at [random_points_and_area.py](https://github.com/WZBSocialScienceCenter/geovoronoi/blob/master/examples/random_points_and_area.py)
and printet the sum of the areat there
```python
area_sum=0
for a in poly_areas:
   print("area is: %s"%a)
    area_sum=area_sum+a
print("area_sum is: %s"%area_sum)
print("area_sum from shape is: %s"%calculate_polygon_areas([area_shape], m2_to_km2=True))
```

where I got:
```
area is: 38047.414248663496

area is: 81558.23012468345

area is: 45652.50539830615

area is: 37314.4644019487

area is: 85299.03205647763

area is: 97225.72636558591

area is: 60036.51052754671

area is: 124761.16667811942

area is: 128687.40068640596

area is: 28103.058823670108

area is: 68784.31109230645

area is: 36575.84996001104

area is: 16695.936399656446

area is: 15257.965532032309

area_sum is: 863999.5722954138

area_sum from shape is: [863999.57229541]
```
But according to [Wikipedia](https://de.wikipedia.org/wiki/Spanien) it should be: 505.970 km²

**Comment by internaut** [comment]
Thanks for spotting this. I used the wrong projection before calculating the areas. One should *always* use an Equal Area projection before calculating areas. I switched to [LAEA Europe](http://epsg.io/3035) projection and now the sum is almost as reported on Wikipedia: 

```
areas in km²:
[19766.86024891 31168.503297   34305.73485662 31272.51239666
 26466.88487366 33067.69869796 31443.55697406 30221.83664307
 58889.06936024 20570.89231156 26280.49994667 22134.7166086
 39027.36182935 68215.05103782 18857.893836   10619.19585911]
sum:
502308.2687772701
```

The small difference comes from the fact that the example only uses mainland Spain without the islands.

You should make sure to use an Equal Area projection in your project, too!
